# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

r_packages:
  - rmarkdown
  - devtools

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev

# r_build_args: "--no-build-vignettes"
